import '../styles/globals.scss'

import type { Metadata } from "next";

import { circe_font } from "./fonts";
import clsx from 'clsx';

export const metadata: Metadata = {
  title: "Издание",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body
        className={clsx(
          `${circe_font.variable} font-sans`,
        )}
      >
        {children}
      </body>
    </html>
  );
}
