version: "3.8"


networks:
    izdn:

services:
    nginx-izdn:
        container_name: nginx-izdn
        image: nginx:stable-alpine
        # restart: always

        ports:
            - 8085:8085
        # - 40:40

        volumes:
            - ./conf/nginx.conf:/etc/nginx/nginx.conf

        networks:
            - izdn

    django-izdn:
        container_name: django-izdn
        build:
            dockerfile: conf/dev.django.Dockerfile
            context: .
        command: bash -c "while true; do echo 'I am alive!'; sleep 3600; done"
        ports:
            - 8005:8005
        environment:
            - C_FORCE_ROOT=true
        links:
            - postgres-izdn:postgres-izdn.local
        volumes:
            - ./backend:/backend
        depends_on:
            - nginx-izdn
        networks:
            - izdn
            
    postgres-izdn:
        container_name: postgres-izdn
        image: postgres:15.3
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
        volumes:
            - ./conf/init.sql:/docker-entrypoint-initdb.d/init.sql
            - postgres-volume-izdn:/var/lib/postgresql/data

    frontend-izdn:
        container_name: frontend-izdn
        image: node:20.12.1
        build:
            dockerfile: conf/frontend.Dockerfile
            context: .
        working_dir: /app
        ports:
            - 3005:3005
        volumes:
            - ./frontend:/app
        depends_on:
            - django-izdn
        networks:
            - izdn

volumes:
    postgres-volume-izdn:
    pgadmin-volume-izdn:
        

            